import './globals.css';
import { Metadata } from 'next';
import { AppConfig } from '@/utils/AppConfig';
import { Header, Footer } from '@/containers';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    ...AppConfig,
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="w-full" suppressHydrationWarning={true}>
        <main className="min-h-screen lex flex-col items-center justify-between">
          <Header user={session?.user} />
          <main>{children}</main>
          <Footer />
        </main>
      </body>
    </html>
  );
}
